# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-04 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='myTask',
        ),
    ]
