# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-04 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0002_auto_20201104_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myTask',
            new_name='Task',
        ),
    ]
